# Generated by Django 5.0.3 on 2024-03-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='desctiption',
            field=models.CharField(max_length=300),
        ),
    ]
