# Generated by Django 5.0.3 on 2024-03-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_streamer_desctiption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='desctiption',
            new_name='description',
        ),
    ]
