# Generated by Django 5.0.3 on 2024-03-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_desctiption_streamer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='video_preview',
            field=models.FileField(upload_to='video_previews/'),
        ),
    ]
