# Generated by Django 5.0.3 on 2024-03-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_streamer_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='instagram_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='twitch_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
