# Generated by Django 5.0.3 on 2024-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_streamer_instagram_url_streamer_twitch_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
