# Generated by Django 5.0.3 on 2024-03-24 19:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_streamer_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_attribute', models.FileField(upload_to=api.models.StreamerAttribute.get_upload_path)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.streamer')),
            ],
        ),
    ]
