# Generated by Django 5.0.3 on 2024-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_streamerattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamerattribute',
            name='filter',
            field=models.CharField(choices=[('animation', 'Анимация'), ('cloth', 'Одежда')], default='animation', max_length=10),
            preserve_default=False,
        ),
    ]
