# Generated by Django 5.0.3 on 2024-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_streamer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamerattribute',
            name='filter',
            field=models.CharField(choices=[('animations', 'Анимация'), ('cloth', 'Одежда')], max_length=10),
        ),
    ]
