# Generated by Django 5.0.3 on 2024-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_streamerattribute_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamerattribute',
            name='video_attribute',
            field=models.FileField(upload_to='video_attribute/'),
        ),
    ]
