# Generated by Django 5.0.3 on 2024-03-24 21:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_streamerattribute_video_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamerattribute',
            name='video_attribute',
            field=models.FileField(upload_to=api.models.StreamerAttribute.get_upload_path),
        ),
    ]
